=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/7operaciones.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="operaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="operacion" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="venta">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulosVendidos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" maxOccurs="20">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="5"></xs:minLength>
                                                                <xs:maxLength value="50"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="cantidad" type="xs:integer" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="entregado" type="xs:boolean"></xs:element>
                                        <xs:element name="importe">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"></xs:minInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element> 
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="compra">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulosComprados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" maxOccurs="20">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="5"></xs:minLength>
                                                                <xs:maxLength value="50"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="cantidad" type="xs:integer" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="proveedor" type="xs:string"></xs:element>
                                        <xs:element name="fechaCompra" type="xs:date"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/7operaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Se desea crear un formato de intercambio de datos para una empresa mayorista de libros 
con el fin de que sus distintos programas puedan manejar la información interna. 
El formato de archivo debe tener la siguiente estructura:
El elemento raíz es «operaciones».
Dentro de «operaciones» hay uno o más elementos «operacion».
Una «operacion» puede ser «venta», «compra», o cualquier combinación y secuencia de ellas, pero debe haber al menos una.
Una venta tiene dentro un elemento «titulosvendidos». Dentro de «titulosvendidos» se almacenan estos datos:
Uno o más elementos «título».
La cantidad total de libros vendidos.
Puede haber un elemento «entregado» que indique si la entrega se ha realizado.
Debe haber un elemento importe con un atributo obligatorio llamado «moneda».
Una compra tiene dentro un elemento «tituloscomprados». Dentro de él hay esto:
Uno o más elementos «titulo»
Un «proveedor».
Una fecha de compra, que debe desglosarse en elementos día, mes y año -->

<operaciones xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="7operaciones.xsd">
    <operacion>
        <compra>
            <titulosComprados cantidad="20">
                <titulo>Venedetti</titulo>
            </titulosComprados>
            <proveedor>Lorem</proveedor>
            <fechaCompra>2023-02-15</fechaCompra>
        </compra>
    </operacion>
    <operacion>
        <venta>
            <titulosVendidos cantidad="34">
                <titulo>Supaduapilupi</titulo>
            </titulosVendidos>
            <entregado>true</entregado>
            <importe>10.2</importe>
        </venta>
    </operacion>
</operaciones>
