=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/listaCompras.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listaCompras">
    <xs:complexType>
      <xs:choice>
        <xs:element name="venta" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ventaCredito" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="fechaFinPago" type="xs:string"/>
                    <xs:element name="cantidadCredito" type="xs:integer" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="ventaInmediata" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cantidad" type="xs:integer"/>
                    <xs:element name="divisa" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/listaCompras.xml
<?xml version="1.0" encoding="UTF-8"?>

<listaCompras xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="listaCompras.xsd">
    <venta>
        <ventaCredito>
            <fechaFinPago>22-5-2026</fechaFinPago>
            <cantidadCredito>20</cantidadCredito>
        </ventaCredito>
    </venta>
    <venta>
        <ventaInmediata>
            <cantidad>10</cantidad>
            <divisa>euro</divisa>
        </ventaInmediata>
    </venta>
</listaCompras>
