<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listaCompras [
    <!ELEMENT listaCompras (venta+)>
    <!ELEMENT venta (ventaCredito | ventaInmediata)>  <!-- la " | " es un o exclusivo, es decir o uno u otro, no los dos-->
    <!ELEMENT ventaCredito (fechaFinPago?, cantidadCredito)>
    <!ELEMENT fechaFinPago (#PCDATA)>
    <!ELEMENT cantidadCredito (#PCDATA)>
    <!ELEMENT ventaInmediata (cantidad, divisa)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT divisa (#PCDATA)>
]>
<listaCompras>
    <venta>
        <ventaCredito>
            <fechaFinPago>22-5-2026</fechaFinPago>
            <cantidadCredito>20</cantidadCredito>
        </ventaCredito>
    </venta>
    <venta>
        <ventaInmediata>
            <cantidad>10</cantidad>
            <divisa>euro</divisa>
        </ventaInmediata>
    </venta>
</listaCompras>