=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/prueba/pt3/pt3_paEd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pablo JimÃ©nez y Edu Mendieta -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listaSistemas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sistemaEstelar" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="masa" type="xs:integer"/>
                            <xs:element name="fecha" type="xs:date" minOccurs="0"/>
                            <xs:element name="planetas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="planeta" minOccurs="0" maxOccurs="10">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombrePlaneta" type="xs:string"/>
                                                    <xs:element name="tipo" type="xs:string"/>
                                                    <xs:element name="habitable" type="xs:boolean"/>
                                                    <xs:element name="satelites">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="satelite" minOccurs="0" maxOccurs="5">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="periodoOrbital" type="xs:integer"/>
                                                                            <xs:element name="atmosfera" type="xs:boolean"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pavelio1303/LENGUAJES-DE-MARCAS/XSD+XML/prueba/pt3/pt3_paEd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pablo Jiménez y Edu Mendieta -->
<!--- Se desea almacenar información de sistemas estelares.
- Cada sistema estelar tiene una lista de planetas (entre 0 y 10).
- Cada planeta tiene una lista de satélites (entre 0 y 5).

- De los sistemas estelares queremos conocer su nombre, la masa y la fecha de descubrimiento (opcional).
- De los planetas queremos conocer su nombre, tipo y si es habitable o no.
- De los satélites queremos conocer su periodo orbital (horas), y si tiene atmósfera o no. -->
<listaSistemas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="pt3_paEd.xsd">
    <sistemaEstelar>
        <nombre>Alfa Tauri</nombre>
        <masa>34</masa>
        <fecha>2054-02-12</fecha>
        <planetas>
            <planeta>
                <nombrePlaneta>Júpiter</nombrePlaneta>
                <tipo>gaseoso</tipo>
                <habitable>true</habitable>
                <satelites>
                    <satelite>
                        <periodoOrbital>29</periodoOrbital>
                        <atmosfera>false</atmosfera>
                    </satelite>
                </satelites>
            </planeta>
        </planetas>
    </sistemaEstelar>
    <sistemaEstelar>
        <nombre>Beta Domo</nombre>
        <masa>79</masa>
        <planetas>
            <planeta>
                <nombrePlaneta>Centollo</nombrePlaneta>
                <tipo>rocoso</tipo>
                <habitable>false</habitable>
                <satelites>
                    <satelite>
                        <periodoOrbital>3</periodoOrbital>
                        <atmosfera>false</atmosfera>
                    </satelite>
                    <satelite>
                        <periodoOrbital>27</periodoOrbital>
                        <atmosfera>false</atmosfera>
                    </satelite>
                </satelites>
            </planeta>
            <planeta>
                <nombrePlaneta>Cangrejo</nombrePlaneta>
                <tipo>oceanico</tipo>
                <habitable>true</habitable>
                <satelites>
                    <satelite>
                        <periodoOrbital>8</periodoOrbital>
                        <atmosfera>true</atmosfera>
                    </satelite>
                </satelites>
            </planeta>
        </planetas>
    </sistemaEstelar>
</listaSistemas>
